### ISSUE TITLE
probleme wuth the docker bluid command 

### ISSUE THREAD

**Issue by Balragh** [Nereg/ARKMonitorBot#12]
`Running command git clone -q https://github.com/Nereg/python-a2s /tmp/pip-install-3t3ncqlc/python-a2s
  Running command git checkout -q 6165cebc6420c79afb1315a1d9051c79564ce6a5
  fatal: reference is not a tree: 6165cebc6420c79afb1315a1d9051c79564ce6a5
ERROR: Command errored out with exit status 128: git checkout -q 6165cebc6420c79afb1315a1d9051c79564ce6a5 Check the logs for full command output.
WARNING: You are using pip version 19.3; however, version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'bot' failed to build: The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
`
and just for the warn line, my pip version is the 21.0.1 but i dont think this is the issue ^^

docker-compose --version
docker-compose version 1.26.0, build d4451659
tell me if you want more info

**Comment by Balragh** [comment]
user@user-HP-Laptop-15-bs0xx:~/Ark/ARKMonitorBot$ sudo docker-compose up -d --build
Building bot
Step 1/7 : FROM python:3.7.4
 ---> 9fa56d0addae
Step 2/7 : WORKDIR /app
 ---> Using cache
 ---> 4566db955913
Step 3/7 : COPY . /app/
 ---> 408dac03d3c8
Step 4/7 : RUN chmod +x wait-for-it.sh
 ---> Running in a3bf39545e6d
Removing intermediate container a3bf39545e6d
 ---> 4f94fb223f45
Step 5/7 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Running in 0c476418ed1d
Collecting aiodns==2.0.0
  Downloading https://files.pythonhosted.org/packages/da/01/8f2d49b441573fd2478833bdba91cf0b853b4c750a1fbb9e98de1b94bb22/aiodns-2.0.0-py2.py3-none-any.whl
Collecting aiohttp==3.6.2
  Downloading https://files.pythonhosted.org/packages/e3/71/6000eacb8923d9fd07aa8784a8fab4f022ae697f3c2456d7dca75c743dd6/aiohttp-3.6.2-cp37-cp37m-manylinux1_x86_64.whl (1.2MB)
Collecting APScheduler==3.6.3
  Downloading https://files.pythonhosted.org/packages/f3/34/9ef20ed473c4fd2c3df54ef77a27ae3fc7500b16b192add4720cab8b2c09/APScheduler-3.6.3-py2.py3-none-any.whl (58kB)
Collecting discord-ext-menus@ git+https://github.com/Rapptz/discord-ext-menus@cc108bed812d0e481a628ca573c2eeeca9226b42
  Cloning https://github.com/Rapptz/discord-ext-menus (to revision cc108bed812d0e481a628ca573c2eeeca9226b42) to /tmp/pip-install-3t3ncqlc/discord-ext-menus
  Running command git clone -q https://github.com/Rapptz/discord-ext-menus /tmp/pip-install-3t3ncqlc/discord-ext-menus
  Running command git checkout -q cc108bed812d0e481a628ca573c2eeeca9226b42
Collecting arrow==0.15.6
  Downloading https://files.pythonhosted.org/packages/99/b5/1f1c5ef3156f7b514c58613fe56e5670dc56374ab744bd1eb653c95e16b5/arrow-0.15.6-py2.py3-none-any.whl (47kB)
Collecting async-timeout==3.0.1
  Downloading https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting attrs==19.3.0
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting certifi==2020.4.5.1
  Downloading https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-any.whl (157kB)
Collecting cffi==1.14.3
  Downloading https://files.pythonhosted.org/packages/26/d7/1c485a42d59d45f14f27bb93769e56142518c85ddf379dbdad7e42d0ffcd/cffi-1.14.3-cp37-cp37m-manylinux1_x86_64.whl (401kB)
Collecting chardet==3.0.4
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting cryptography==3.2
  Downloading https://files.pythonhosted.org/packages/4a/a8/904c6f56c6018fc0b860510a55ea6123d561d02157f9e0855301afa27749/cryptography-3.2-cp35-abi3-manylinux2010_x86_64.whl (2.6MB)
Collecting dblpy==0.3.4
  Downloading https://files.pythonhosted.org/packages/03/a8/ebc36b7284279ee9ee6b30c151ab32d92ac311493b8a6b16faa6ff2a6ff9/dblpy-0.3.4-py3-none-any.whl
Collecting deepdiff==5.0.2
  Downloading https://files.pythonhosted.org/packages/67/26/49ccae53188f3bbe1fb6dd77721dd853b5eb5d72a932013931c429713839/deepdiff-5.0.2-py3-none-any.whl (60kB)
Collecting discord.py==1.3.4
  Downloading https://files.pythonhosted.org/packages/e9/d4/1b6e6ed08d9cfb6b31ae6eae7cbb57373c153e9f1a7037b369579dccb0b2/discord.py-1.3.4-py3-none-any.whl (676kB)
Collecting idna==2.9
  Downloading https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl (58kB)
Collecting importlib-metadata==1.6.0
  Downloading https://files.pythonhosted.org/packages/ad/e4/891bfcaf868ccabc619942f27940c77a8a4b45fd8367098955bb7e152fb1/importlib_metadata-1.6.0-py2.py3-none-any.whl
Collecting jsonpickle==1.4.1
  Downloading https://files.pythonhosted.org/packages/af/ca/4fee219cc4113a5635e348ad951cf8a2e47fed2e3342312493f5b73d0007/jsonpickle-1.4.1-py2.py3-none-any.whl
Collecting multidict==4.7.6
  Downloading https://files.pythonhosted.org/packages/85/b8/a9fe777dab4c6aa067b516a34fe995213707e490ea1e72f823949a830a6a/multidict-4.7.6-cp37-cp37m-manylinux1_x86_64.whl (149kB)
Collecting mysql-connector-python==8.0.20
  Downloading https://files.pythonhosted.org/packages/ea/81/8903dbd4dc128300d00788a91faeb1cfb814fb31f287909a440a8aaf0417/mysql_connector_python-8.0.20-cp37-cp37m-manylinux1_x86_64.whl (14.8MB)
Collecting ordered-set==4.0.2
  Downloading https://files.pythonhosted.org/packages/f5/ab/8252360bfe965bba31ec05112b3067bd129ce4800d89e0b85613bc6044f6/ordered-set-4.0.2.tar.gz
Collecting protobuf==3.12.2
  Downloading https://files.pythonhosted.org/packages/07/63/2c505711827446bfdb544e7bcc0d7694b115d22d56175902a2581fe1172a/protobuf-3.12.2-cp37-cp37m-manylinux1_x86_64.whl (1.3MB)
Collecting psutil==5.7.2
  Downloading https://files.pythonhosted.org/packages/aa/3e/d18f2c04cf2b528e18515999b0c8e698c136db78f62df34eee89cee205f1/psutil-5.7.2.tar.gz (460kB)
Collecting pycares==3.1.1
  Downloading https://files.pythonhosted.org/packages/d3/ea/6367930636a9859cc9ea8cb738a3e0c4f9929c596806214d5df4c48565db/pycares-3.1.1-cp37-cp37m-manylinux2010_x86_64.whl (228kB)
Collecting pycparser==2.20
  Downloading https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)
Collecting python-a2s@ git+https://github.com/Nereg/python-a2s@6165cebc6420c79afb1315a1d9051c79564ce6a5
  Cloning https://github.com/Nereg/python-a2s (to revision 6165cebc6420c79afb1315a1d9051c79564ce6a5) to /tmp/pip-install-3t3ncqlc/python-a2s
  Running command git clone -q https://github.com/Nereg/python-a2s /tmp/pip-install-3t3ncqlc/python-a2s
  Running command git checkout -q 6165cebc6420c79afb1315a1d9051c79564ce6a5
  fatal: reference is not a tree: 6165cebc6420c79afb1315a1d9051c79564ce6a5
ERROR: Command errored out with exit status 128: git checkout -q 6165cebc6420c79afb1315a1d9051c79564ce6a5 Check the logs for full command output.
WARNING: You are using pip version 19.3; however, version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'bot' failed to build: The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1

**Comment by Nereg** [comment]
Please pull from [dev](https://github.com/Nereg/ARKMonitorBot/tree/dev) branch. There is a fix for it
