### ISSUE TITLE
change it

### ISSUE THREAD

**Issue by helish88** [Nereg/ARKMonitorBot#7]
https://github.com/Nereg/ARKMonitorBot/blob/ace113c4138b418a08ba1a794f4fe526bb2c7944/src/main.py#L87
use this instead of your check
```py
@commands.has_permissions(manage_roles = True)

**Comment by Nereg** [comment]
I check if bot have permissions in another channel `@commands.has_permissions(manage_roles = True)` will check if bot have permissions in current channel.
